# Generated by Django 5.0.7 on 2024-08-17 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TutionApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=255)),
                ('fee', models.IntegerField()),
                ('course_duration', models.CharField(max_length=255)),
                ('syllabus', models.FileField(blank=True, null=True, upload_to='syllabus_pdfs/')),
            ],
        ),
    ]
