from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('admin_panel/', views.admin_panel, name='admin_panel'),
    path('login/', views.user_login, name='login'),
    path('login1/', views.login1, name='login1'),
    path('add_course/', views.add_course, name='add_course'),
    path('add_coursedb/', views.add_coursedb, name='add_coursedb'),
    path('teacher_register/', views.teacher_register, name='teacher_register'),
    path('teacher_registerdb/', views.teacher_registerdb, name='teacher_registerdb'),
    path('apd/', views.apd, name='apd'),
    path('user_approve/<int:k>/', views.approve, name='approve'),
    path('user_disapprove/<int:k>/', views.disapprove, name='disapprove'),
    path('student_register/', views.student_register, name='student_register'),
    path('student_registerdb/', views.student_registerdb, name='student_registerdb'),
    path('manage_course/', views.manage_course, name='manage_course'),
    path('teacher_details/', views.teacher_details, name='teacher_details'),
    path('delete_teacher/<int:k>/', views.delete_teacher, name='delete_teacher'),
    path('student_details/', views.student_details, name='student_details'),
    path('delete_student/<int:k>/', views.delete_student, name='delete_student'),
    path('teacher_attendance/', views.teacher_attendance, name='teacher_attendance'),
    path('teach_attend/', views.teach_attend, name='teach_attend'),
    path('vta/', views.vta, name='vta'),
    path('view_teach_attend/', views.view_teach_attend, name='view_teach_attend'),
    path('show_teach_attend/', views.show_teach_attend, name='show_teach_attend'),
    path('assign/', views.assign, name='assign'),
    path('assign_teacher/<int:student_id>/<int:teacher_id>/', views.assign_teacher, name='assign_teacher'),
    path('teacher_panel/', views.teacher_panel, name='teacher_panel'),
    path('student_attendence', views.student_attendence, name='student_attendence'),
    path('stud_attend/', views.stud_attend, name='stud_attend'),
    path('vsta/', views.vsta, name='vsta'),
    path('view_stud_attend/', views.view_stud_attend, name='view_stud_attend'),
    path('show_stud_attend/', views.show_stud_attend, name='show_stud_attend'),
    path('teach_attendence/', views.teach_attendence, name='teach_attendence'),
    path('show_tt_attend/', views.show_tt_attend, name='show_tt_attend'),
    path('view_syllabus/', views.view_syllabus, name='view_syllabus'),
    path('view_sylla', views.view_sylla, name='view_sylla'),
    path('teacher_student/', views.teacher_student, name='teacher_student'),
    path('re_pas/', views.re_pas, name='re_pas'),
    path('reset_password/', views.reset_password, name='reset_password'),
    path('student_panel/', views.student_panel, name='student_panel'),
    path('show_st_attend/', views.show_st_attend, name='show_st_attend'),
    path('std_attendence/', views.std_attendence, name='std_attendence'),
    path('view_st_syllabus/', views.view_st_syllabus, name='view_st_syllabus'),
    path('view_st_sylla/', views.view_st_sylla, name='view_st_sylla'),
    path('re_paswd/', views.re_paswd, name='re_paswd'),
    path('reset_st_password/', views.reset_st_password, name='reset_st_password'),
    path('student_profile/', views.student_profile, name='student_profile'),
    path('student_attendence_admin/', views.student_attendence_admin, name='student_attendence_admin'),
    path('task/', views.task, name='task'),
    path('assign_task/', views.assign_task, name='assign_task'),
    path('view_task/', views.view_task, name='view_task'),
    path('tasks/', views.tasks, name='tasks'),
    path('submit_task/', views.submit_task, name='submit_task'),
    path('submit/', views.submit, name='submit'),
    path('submitted/', views.submitted, name='submitted'),


    
]
